In [1]:
import numpy as np
import sys
from copy import deepcopy
import matplotlib.pyplot as plt
import pandas as pd
from classevy.klas import StudentGroup, Klas, Plan, PlanPopulation

# 1. Upload the csv file (or later xlsx)

In [2]:
students = StudentGroup('../data/students.csv')

## backend:
- verify the data
- obtain columns which can be optimized for (spread_... + preferences_satisfied)
    - where to get this info? from student or plan or population???

# 2. Select the columns to optimize

In [3]:
pop = PlanPopulation(students, 20, 2)
all_goals = pop.default_goals_dict
all_goals

{'spread_score_math': 'min',
 'spread_score_spelling': 'min',
 'spread_gender': 'min',
 'spread_learning_advantage': 'min',
 'spread_size': 'min'}

In [4]:
pop.goals_dict = all_goals
pop.goals_dict

{'spread_score_math': 'min',
 'spread_score_spelling': 'min',
 'spread_gender': 'min',
 'spread_learning_advantage': 'min',
 'spread_size': 'min'}

# 3. Hit GO

## backend:
4. run for a number of generations
5. sort the pareto front by sum and optionally display
6. optionally: let user choose solution
7. present solution for download

In [5]:
pop.run()

In [21]:
front = pop.pareto()
len(front)

20

In [7]:
front['sum'] = sum([front[col] for col in pop.goals_names])

In [8]:
front.sort_values('sum')

,Individual,spread_score_math,spread_score_spelling,spread_gender,spread_learning_advantage,spread_size,assignment_check,sum
9,<classevy.klas.PlanPopulation.__init__.<locals...,0.445055,0.46978,0.247253,0.035714,0.5,True,1.697802
12,<classevy.klas.PlanPopulation.__init__.<locals...,0.445055,0.46978,0.247253,0.035714,0.5,True,1.697802
14,<classevy.klas.PlanPopulation.__init__.<locals...,0.519231,0.46978,0.395604,0.035714,0.5,True,1.92033
7,<classevy.klas.PlanPopulation.__init__.<locals...,0.45,0.45,0.3,0.033333,1.5,True,2.733333
18,<classevy.klas.PlanPopulation.__init__.<locals...,0.613636,0.357955,0.357955,0.03125,2.5,True,3.860795
19,<classevy.klas.PlanPopulation.__init__.<locals...,0.25,0.333333,0.166667,0.027778,4.5,True,5.277778
8,<classevy.klas.PlanPopulation.__init__.<locals...,0.75,0.0,0.0,0.138889,4.5,True,5.388889
13,<classevy.klas.PlanPopulation.__init__.<locals...,0.5,0.25,0.333333,0.027778,4.5,True,5.611111
4,<classevy.klas.PlanPopulation.__init__.<locals...,0.177632,0.325658,0.059211,0.026316,5.5,True,6.088816
2,<classevy.klas.PlanPopulation.__init__.<locals...,0.266447,0.414474,0.236842,0.026316,5.5,True,6.444079
3,<classevy.klas.PlanPopulation.__init__.<locals...,0.266447,0.503289,0.236842,0.026316,5.5,True,6.532895
1,<classevy.klas.PlanPopulation.__init__.<locals...,0.266447,0.414474,0.414474,0.026316,5.5,True,6.621711
15,<classevy.klas.PlanPopulation.__init__.<locals...,0.289286,0.321429,0.128571,0.025,6.5,True,7.264286
6,<classevy.klas.PlanPopulation.__init__.<locals...,0.192857,0.417857,0.321429,0.025,6.5,True,7.457143
10,<classevy.klas.PlanPopulation.__init__.<locals...,0.482143,0.128571,0.321429,0.025,6.5,True,7.457143
16,<classevy.klas.PlanPopulation.__init__.<locals...,0.289286,0.321429,0.321429,0.025,6.5,True,7.457143
17,<classevy.klas.PlanPopulation.__init__.<locals...,0.289286,0.321429,0.321429,0.025,6.5,True,7.457143
5,<classevy.klas.PlanPopulation.__init__.<locals...,0.385714,0.225,0.321429,0.025,6.5,True,7.457143
0,<classevy.klas.PlanPopulation.__init__.<locals...,0.289286,0.321429,0.321429,0.025,6.5,True,7.457143
11,<classevy.klas.PlanPopulation.__init__.<locals...,0.368182,0.081818,0.081818,0.022727,8.5,True,9.054545

In [9]:
best_plan = front.sort_values('sum').iloc[0].values[0]

In [10]:
best_plan.classes_gender

[0.5714285714285714, 0.07692307692307693]

In [11]:
students['gender'].mean()

0.3333333333333333

In [12]:
best_plan.classes[0].print_names()

luuk
pat
jos
tia
karl
siem
ahmed
pius
darius
mario
marie
pieter
rinus
karla

In [13]:
best_plan.classes[1].print_names()

pol
katrien
mo
marius
maria
peter
pier
pieter
maarten
sanne
carla
clara
klara

In [14]:
best_plan.classes_size

[14, 13]

In [15]:
best_plan.classes_gender

[0.5714285714285714, 0.07692307692307693]

In [16]:
best_plan.classes_score_math

[7.428571428571429, 6.538461538461538]

In [17]:
best_plan.check_assignment()

True

In [18]:
for plan in front['Individual']:
    print(plan.check_assignment())

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True

In [19]:
best_plan.students

,name,score_math,score_spelling,gender,learning_advantage,not_together,together,preferences,options,dna_assignment,final_assignment,pref_satisfied
number,,,,,,,,,,,,
1,luuk,10,8,1,1,"(4,)","(2,)","(3, 6, 17)",[0],0,0.0,1.0
2,pat,9,7,1,0,(),"(1,)","(5, 9, 27)",[0],0,0.0,1.0
3,jos,8,6,1,0,"(6,)",(),"(2, 1, 21)",[0],0,0.0,2.0
4,pol,7,9,1,0,"(1,)",(),"(5, 6, 7)",[1],0,1.0,2.0
5,katrien,6,7,-1,0,(),(),"(6, 7, 23)","[0, 1]",0,1.0,1.0
6,mo,5,5,1,0,"(3, 8)",(),"(12, 5, 25)",[1],0,1.0,2.0
7,tia,6,7,-1,0,(),"(8,)","(8, 17, 23)",[0.0],1,0.0,2.0
8,karl,7,4,1,0,"(6,)","(7,)","(9, 27, 14)",[0.0],1,0.0,2.0
9,siem,8,3,1,0,(),(),"(10, 18, 19)","[0, 1]",1,0.0,2.0
10,ahmed,8,8,1,0,(),"(11,)","(12, 5, 25)",[0],1,0.0,1.0
11,pius,5,6,1,0,(),"(10,)","(2, 4, 6)",[0.0],0,0.0,1.0
12,darius,4,5,1,-1,"(20,)",(),"(10, 18, 19)",[0],1,0.0,2.0
13,marius,6,7,1,0,(),(),"(5, 6, 7)","[0, 1]",1,1.0,2.0
14,mario,9,6,1,0,(),(),"(1, 3, 5)","[0, 1]",1,0.0,2.0
15,maria,7,8,-1,0,(),(),"(5, 6, 7)","[0, 1]",1,1.0,2.0
16,marie,8,9,-1,0,(),(),"(3, 6, 17)","[0, 1]",0,0.0,1.0
17,peter,9,8,1,0,(),(),"(9, 13, 14)","[0, 1]",1,1.0,1.0
18,pieter,10,7,1,1,(),(),"(2, 1, 21)","[0, 1]",0,0.0,2.0
19,pier,6,6,1,0,(),(),"(7, 19, 17)","[0, 1]",1,1.0,2.0
20,pieter,8,7,1,0,"(12,)",(),"(3, 22, 1)",[1],0,1.0,1.0
21,maarten,6,8,1,0,(),(),"(3, 6, 17)","[0, 1]",1,1.0,2.0
22,sanne,7,7,-1,0,(),(),"(4, 8, 9)","[0, 1]",0,1.0,1.0
23,rinus,8,6,1,0,(),(),"(5, 8, 10)","[0, 1]",1,0.0,2.0
24,karla,4,5,-1,0,(),(),"(10, 11, 16)","[0, 1]",0,0.0,3.0
25,carla,5,6,-1,0,(),(),"(6, 7, 23)","[0, 1]",0,1.0,1.0
26,clara,6,7,-1,0,(),(),"(6, 7, 23)","[0, 1]",1,1.0,1.0
27,klara,7,8,-1,0,(),(),"(9, 11, 19)","[0, 1]",1,1.0,1.0

In [20]:
pop.summary()

{'spread_score_math': 0.37679948341132563,
 'spread_score_spelling': 0.32987421569658404,
 'spread_gender': 0.2567196947789053,
 'spread_learning_advantage': 0.03345805327713223,
 'spread_size': 4.75,
 'assignment_check': 1.0}